---
bibliography: [library.bib]
biblio-style: apalike
---

\newpage

# Epilogue

Addressing (some of the) epistemological issues scholarly research faces has been the underlying focus of the this dissertation, but the pieces have a larger and more important context. The last seven years, since the start of my first personal epistemological crisis, the need to address these issues has become almost unequivocal. Different kinds of evidence dripped in from various fields [@doi:10.1371/journal.pone.0200303;@doi:10.1016/j.respol.2014.05.002;@doi:10.1097/phh.0000000000000694;@doi:10.1146/annurev-criminol-032317-091849] and new options have become available to raise the epistemological bar [e.g., Registered Reports; @doi:10.1016/j.cortex.2012.12.016]. Despite some claims of publication bias not necessarily being bad for science [@doi:10.7287/peerj.preprints.1968v4;@doi:10.1371/journal.pone.0066463;@mitchell] and that the reproducibility crisis is harmful rhetoric [@doi:10.1073/pnas.1708276114] and overblown [@doi:10.1073/pnas.1708272114], it seems that readiness for meaningful reform has spread. Hence, it surprises me that exactly such meaningful reform largely remains absent. I recognize and valua the great work done in these last seven years to raise the epistemological bar, but is it enough? I think there is a case to make that this is only the start and that there is a need for a stronger program of reform moving forward.

Short-term progress on some epistemological issues has been made, but it begs the question whether these changes are sufficient. Many of the suggested reforms fail the test of the five scholarly communication functions quite easily. 
For example, badges labeling the sharing of data, preregistration of hypotheses, or sharing of materials may incentivize this behavior [@doi:10.1371/journal.pbio.1002456
;@doi:10.12688/f1000research.13477.2], but hardly do these badges raise awareness of that information. The URLs linking to that information are typically only available in the (paywalled) articles and not widely indexed.
Preregistrations, if publicly available, are not well preserved. [AsPredicted.org](https://aspredicted.org) is someone's side project that could disappear any day. Moreover, nobody knows how many preregistrations occur on this platform and how many ultimately get publicized, facilitating selective registration of preregistrations in the literature. Another preregistration service, the Open Science Framework, has a rainy-day fund that would sustain read-only access to preregistrations for fifty years, which is not long-term preservation in the grand scheme of things. 
Registered Reports may still have selective registration through any biased acceptance of studies on topic or design in the review process, despite eliminating the selection based on results. 
Selective publication for clinical trials is effectively eliminated by federal regulations in the United States of America through central registration yet there remains selective publication of approximately 50% [@doi:10.1371/journal.pmed.1000144;@doi:10.1136/bmj.k2130]. In theory publication bias based on results is eliminated, but in practice it may not be.
<!-- We may be able to detect data fabrication, but only if publication bias is eliminated (Chapter 6).  -->
Open access publishing is facilitated by new publishing models, but the (excessive) prices involved disincentivizes researchers<!--  with restricted financial means -->. 
Giving access through self-archival threatens the content integrity of what readers view by necessitating the archival of a different version (i.e., accepted manuscript) than that which is ultimately published (i.e., typeset manuscripts). 
New journals improve registration and certification when they no longer select on results and require reproducible results [e.g., @doi:10.15626/mp2017.1001], but may not create the needed momentum to change incentive systems because universities still indirectly punish those who publish in newer journals [a journal only gets a Journal Impact Factor after at least 2 years; @doi:10.1371/journal.pone.0006022]. 
The attention on higher statistical power [e.g., @doi:10.1038/s41562-016-0021] and potential lower statistical significance levels [@doi:10.1038/s41562-017-0189-z] may create additional selection criteria to bias publication, instead of facilitating the registration of all results. 
Researchers voice moral support for unbiased access to knowledge but incentive systems promote publishing with journals that require the unnecessary transfer of all copyrights. 
Sci-Hub provides unbiased access to research papers but this has been deemed illegal [@doi:10.1038/nature.2017.22971]. 
Universities claim to promote better science but are driven to achieve higher rankings in an increasingly privatized and competitive environment [@isbn:9781786631398], which in turn is driven by the problematic incentive structures that undermine that goal. 
These are some of the main examples that may indicate how these epistemological issues are networked, extensive, complex, and tied to the functions of a scholarly communication system.

The network of epistemological issues is difficult to navigate and scientific populism has created readiness for change but has stopped short of providing  meaningful and coherent set of reforms. Populism has a negative connotation, but simply implies that it builds broad support by highlighting issues people care about. Scientific populism for that reason has been a great instigator of the awareness in the last decade. However, populism is only worthwhile if it subsequently provides meaningful reform. For example, the issue of selective publication is urgent and highly wasteful [@doi:10.1371/journal.pone.0084896] but when we aim to address it by stating things equivalent to "don't do it anymore" we waive the practical considerations of people in trying to not do it anymore [@doi:10.5281/zenodo.826643]. In other words, scientific populism may raise awareness but does not meaningfully deal with these issues in a way that can achieve real change. Researchers involved in these kinds of studies might not feel obliged to take up the role of political persuasion [@doi:10.1177/1745691615609918] but by calling for changes they take an inherently political position to begin with. Moreover, some reforms have been proposed, but as I outlined before, these are short-term and 'fix' one thing while breaking another. As such, I consider these ameliorative. It seems like even the National Academy of Sciences in the U.S.A. resorts to this. They recently released an "Open Science by Design" report [@doi:10.17226/25116], which seems to outline more what should be addressed than how to meaningfully reform. If of the position that the system is too broken to be ameliorated into sustainability, the only other viable option is reform more fundamentally.

Transparency is often heralded as the key to making fundamental progress on raising the epistemological bar, assuming that making things visible is sufficient to improving the situation. However, what the debate may fail to realize is that transparency is in itself a form of obfuscation [@isbn:9780262029735]. For example, legal teams may bury their opponents by being transparent, sharing troves of documents such that the information is too vast to reasonably comprehend. A simpler scenario of obfuscation is Where's Waldo: One excentric individual in a sea of people is difficult to find. In more statistical terms, the prevalence of relevant information is likely to decrease by sole and transparency. The "saturation of science" through excessive amounts of information is not new [@isbn:0231049560;@doi:10.1080/1047840X.2012.701161] and is multiplied by dumping information without making it more digestable. As such, transparency alone might obfuscate to such extent that science becomes less accessible instead of more, fueling work pressure and mental disorders already too prevalent in scholarly research [@doi:10.1038/nbt.4089]. Additionally, transparency is a form of (counter)surveillance [@isbn:9780262029735], facilitating audit cultures to check (and reprimand lack of) adherence to new policies. This might help explain why some researchers do not feel empowered by the idea of sharing everything they do [@doi:10.1177/1745691617739421] without the act of doing so providing valuable changes to the knowledge production process or even detracting from it through increased bureaucracy and auditing.

Transparency alone is insufficient because it obfuscates and ultimately does not fundamentally change the knowledge generation process. As such, transparency in itself is an ameliorative and short-term process that does not facilitate long term sustainability in the epistemological process, but simply puts it in a more public arena. Through this public nature, we might improve some facets such as detecting data fabrication or irreproducibility, but we do not change how power is distributed. We currently see a power shift towards a new generation, but we need to change power structures to prevent similar issues of inertia arising when transparency in time will be insufficient (as I argue it already is). It is extremely difficult to ameliorate issues after the fact if the status quo is more entrenched. 

The process of working open provides an additional layer to transparency and more fundamentally changes the knowledge generation process. Working open is a process of co-creation, where the outcome is not necessarily driven individualistically and then shared publicly as in purely transparent practices, but where individuals or teams collectively work towards a common goal and the inclusion of those teams is not on an invitation only basis. These teams can converge and disperse as required. Working open stems from the open source community (e.g., [https://wiki.mozilla.org/Working_open](https://wiki.mozilla.org/Working_open)), where responsibility to create is distributed through lowered opportunity costs, heightened empowerment of individuals in participation, and increased collective returns through diverse inputs. This empowerment to participate comes from collectively making information more digestable (e.g., documentation) as opposed to having people sort out the information themselves. As a consequence (ideally), when an open source project is not to your liking you may create a copy and adjust it to your liking. Or, you may join the co-creating process and share your (ideas for) adjustments there. For this co-creation to be possible, there is the need for more than sole transparency; reuse requires permissions, co-creation requires contribution guidelines, accessible documentation, community engagement, and civil conduct to allow people to feel welcome and able to participate in that process regardless of their background. These kinds of co-creative projects are spreading beyond open source into science through for example the Psychological Science Accelerator [@doi:10.1126/science.aar4464].
The process of co-creation is not without its own faults [e.g., gender biases in accepting contributions; @doi:10.7717/peerj-cs.111] and engaging underrepresented groups is an active responsibility to make sure the pool of co-creators becomes heterogeneous. Moreover, universities's hierarchical nature and frequent deference to authority (amongst other toxic behaviors) has bred a scholarly culture that is not welcoming to people from more diverse- and non-traditional origins, which hampers the co-creating process. For example, in the U.S.A. 58% of all female university employees are estimated to have experienced sexual harassment [@doi:10.17226/24994] and graduate students are six times as likely to experience mental illness when compared too the general population [@doi:10.1038/nbt.4089]. Sexism, racism, and other direct or indirect behaviors that create unnecessary mental stress are intolerable in themselves and prevent an environment where diverse co-creation can take place. Hence, co-creation necessitates culture change in universities to foster an equitable environment where such behaviors are addressed in practice and not only in policies. Only with a healthy culture that actively allows anyone to participate will such co-creation become possible.

Equitable environments and co-creating processes may (more so) be a reality outside of universities than inside, making those spaces promising for raising the epistemological bar in science while at the same time providing a healthier climate for those participating in it. After all, scientific communities outside of universities are likely to be newer than these old institutions and still in the 'bulding-a-culture' phase that is less infested by the already existing incentive structures of science. For example, the Safecast community [[https://blog.safecast.org/](https://blog.safecast.org/); @doi:10.1088/0952-4746/36/2/S82] provides a co-creative process for collecting and analyzing radiation data. Open hardware is built by engineers in the community (e.g., [the nano bGeigei counter](https://blog.safecast.org/bgeigie-nano/)), which is distributed/purchased by individuals who want to contribute data, who in turn collect data that is aggregated in a [public database](https://api.safecast.org/) without restrictions to reuse. Researchers subsequently may reuse the data for scientific purposes [@doi:10.1016/j.jenvrad.2017.01.005;@doi:10.1016/j.jenvrad.2018.04.018], policy makers [@doi:10.1088/0952-4746/36/2/S82]. The individuals involved in parts of this process need not (but can) be involved with the other parts of the process, indicating the modular nature of co-creation. Other examples of such communities include the Biohacking community [@isbn:9780745332802]. If co-creation processes proves to be epistemologically more effective, universities may (and should) lose their role as the main creator of new knowledge in the future (which they have only played for a few centuries).

Knowledge generation processes and their sustainability are inherently driven by those who fund it. The effect of politics on the direction of public research funds is particularly clear in the history of the Human Genome Project, where public funding was being pushed against by Republicans in the U.S.A. Congress [@isbn:9781983033223]. Public funding still has some potential for intervention when there is democratic representation involved. However, with private philanthropic funding the question of how those funders influence research programs and the larger research enterprise is also worth asking [@isbn:9781784780838]. For example, the Bill and Melinda Gates Foundation (BMGF) has attempted to do much for open science, but the Gates legacy at Microsoft was one of anti-open and co-creation [p.72; @isbn:978184964906]. As a more specific example, the BMGF has created (temporary) special privileges where specific journals only allow open publishing for those funded by BMGF [@doi:10.1038/nature.2017.21299;@doi:10.1126/science.aal0767;@doi:10.1038/d41586-018-05729-2], as part of a push to make all their funded research publicly available. Such inequitable consequences can occur, but for private funders there are no accountability or governance mechanisms beyond legal proceedings. Such issues may work to the detriment of progress. The lack of accountability for philanthropic funders to the scholarly community is also troubling when progressive projects rely heavily or even fully depend on private philanthropic funders for their very existence. For example, the Center for Open Science (COS) seems to heavily rely on the Laura and John Arnold Foundation (LJAF) and others for its financial existence [receiving approximately `r round(5682866/(56357+182549+31482), 0)` dollars in non-federal funding for every one dollar of revenue in 2017, up from `r round(4398022/(23557+721438+24238), 0)` in 2016; @cos-finances]. Such potential dependencies are unobjectionable so long as they do not directly or indirectly affect the mission of the COS. However, the LJAF for example also funds algorithmic assessments in legal proceedings [@ljaf-psa], where some other algorithms have been indicated to contain racial bias [@propublica-report;@propublica-analysis], and the use of drones in police surveillance projects [@ljaf-surv]. These domains may seem unrelated to research, but if we consider co-creative processes to be important, people need to feel like they are actually welcome to participate. The funding of projects that exacerbate inequity in society may breed a larger environment of distrust towards projects tied to such funders. Even if this image is only created through association of the COS and LJAF, not speaking up can seem to condone this behavior and result in homogenization of groups involved in the co-creative process. This becomes especially clear if we would replace LJAF in this scenario with philanthropic funders that oppose abortion or gay marriage. Due to financial dependencies, there may be conflicts of interest for such projects to speak out against behaviors that harm the chances of a co-creative process to come into existence that positively facilitates participation instead of providing just a technical option to participate (no matter how hostile the conditions). These examples have not been chosen to lash out at these institutions but to show the larger systemic context and indirect effects funding streams and funding bodies' choices may have.

All things considered, progress since the proposals for scientific utopias I and II [@doi:10.1080/1047840X.2012.692215;@doi:10.1177/1745691612459058] has been considerable but future developments and actions require additional scope. The issues highlighted in the previous paragraphs, amongst others, serve as a basis for that extended scope. Utopias I and II ameliorated to the article-based system, assimilating some of the issues they wanted to overcome. One of my main concerns is that some of the developments so obviously fail key aspects of the scholarly communication functions and as such have substantial difficulties creating a hegemony of new practices and, ultimately, the utopia that has been key to so many people's thinking beyond these two proposals. I recognize that building a new hegemony of ideas that is coherent and practical takes time (I acknowledge my impatience), but there is also ample room for more improvement. Not only does scholarly research need more reform for epistemology's sake, there are pressing issues (e.g., climate change) that require us to do as much as we can.

## Scientific Eutopia III

<!-- I would like to see a scientific utopia that goes beyond addressing key issues that threaten the epistemological value of science itself; I would like to see a scientific utopia that makes it more rewarding to contribute to in the first place. We should not only have full access to knowledge, but that knowledge should be produced in a non-toxic environment. Just in my own personal circle, I know too many cases of unnecessary emotional distress caused by a system that is on the verge of breaking or is already broken. If anything, reforms should, in my opinion, take into account more what the effects are on people and whether they empower  -->

For any eutopia, a set of demands are necessary as design principles. For a scientific eutopia specifically, I think we can and should demand the following (not in any particular order):

  1. science may be conducted anywhere at any time by any one without any restrictions
  <!-- inclusivity, not just profs, etc but also independent researchers -->
  <!-- we see the exclusivity of universities rise, preferring those from higher social strata already [p.133; @isbn:speaking-of-unis] and leenstelsel => needs to be more inclusive -->
  <!-- remove the necessity to stick in toxic cultures -->
  2. communicating science can take place anywhere by anyone (or anything) without any restrictions
  <!-- no  delays/reformatting/lack of -->
  3. communication is made as easy as possible
  <!-- minimal systemic literacy -->
  <!-- no mediating straining factors, eg typesetting -->
  4. full control and responsibility of form and time of communication
  <!-- eg whistleblowers, retractions, corrections, remove bottlenecks -->
  <!-- https://twitter.com/EikoFried/status/806647708853346306 -->
  5. communication invites and facilitates continuous discussion
  <!-- constructive discussoin encourages more communicatoin -->
  <!-- engagement is key -->
  6. communicated science can be consumed anywhere, by anyone (or anything), in any way, for any purpose
  <!-- commercial services, machines -->
  <!-- remove availability biases -->
  7. revenue generated on top of the scientific system must directly fund new scientific efforts
  <!-- publishers would be less objetionable if 10% of their profit margin went to fund science? -->
  8. recognition of all types of communicated scientific efforts, regardless of shape, form, or size
  <!-- credit taxonomy, non-cyclists, programmers, database builders, theorists -->
  <!-- teaching, simplifying, reviewing -->
  9. scientific recognition values incrementality, validity, reliability, and replications over innovativeness, invalidity, unreliability, and spontaneous discovery
  <!-- bullied into bad science -->
  <!-- https://www.nature.com/articles/palcomms2016105#notes -->
  10. immediate and full registration of communicated scientific efforts
  <!-- remove publishability -->
  11. immediate, full, and persistent archival for all communications
  <!--  -->
  12. immediate, full, and persistent availablity of all communications
  <!-- not just archive, we should have them available -->
  <!-- * distributed curation -->
  <!-- a lot of information is removed or censored -->
  13. equitable funding processes
  <!-- basic funding -->
  <!-- no matthew effect http://www.pnas.org/content/early/2018/04/18/1719557115 -->
  <!-- * cooperative pools of required materials -->
  14. communicating science has minimal environmental impact
  <!-- conferences have tremendous impact -->
  <!-- the web uses quiute some energy -->
  15. secure communication channels
  16. participation is not subjected to state- or commercial surveillance and censorship
  17. no monopoly- or oligarchy formation 

These demands only work to create a scientific utopia jointly, because in isolation they fail to address some of larger issues. For example, immediate archival is already possible but requires systemic literacy on the part of the person communicating (e.g., what archival service, what format); by linking the demand for easy communication with the demand for archival, the eutopia demands a communication system that allows for automatic archival when someone chooses to communicate while at the same time making that process a breeze. Such demands implied through combinations of individual demands (i.e., super demands) run into the hundreds and become increasingly complex, hence I will not discuss each of the possibilities. I cover some of the more important super demands next.

First and foremost, facilitating the activity of contributing to science for anyone, anywhere, at any time in any form (demand 1) requires an active effort to minimize entry costs to do so (demands 2, 3, 4, 6, 8). This would require the disassociation of universities as *the* place of science to *a* place of science [see also @10.1371/journal.pone.0202120], but also by making universities *more* accessible to those who want to enter instead of *less* [e.g., by raising tuition fees or making entry dependent on grades, both of which privilege the already privileged; @]. It also requires the unit of recognized contributions to decrease, because scholarly articles are  time consuming and are not the smallest possible contributory unit. Moreover, a smaller minimum contribution also allows for more specialized contributions to occur. As the minimum unit of communication is larger, the amount of privilege and diverse sets of skills needed to go through the steps to make a contribution increases. If contributing can occur in any shape, form, and size (demand 8), individuals may be able to contribute part-time or as a hobby, making it accessible to a larger set of people and allowing the collective effort to benefit from a wider range of specializations. This will require making communication as easy as possible (demand 3) and making sure that all contributions are registered without uncertainty (demand 10). Eliminating the uncertainty of being able to communicate (demand 4) is necessary to make it enticing for people to contribute to begin with. However, eliminating any barriers to communication requires more active, constructive, and continuous discussion (demand 5) such that contributions remain small and may actively be improved upon to raise the epistemological value.

Scientists already aim for active, constructive, and continuous discussion (demand 5), but do so at tremendous environmental cost by in-person meetings. For example, one round trip flight from Western Europe to the east coast of the U.S.A. is approximately two tonnes of $CO_2$ emissions, where two tonnes is the maximum amount one person should produce per year in order to halt climate change ([myclimate.org](https://myclimate.org)). Taking into account the number of people attending conferences (frequently in the hundreds and sometimes in the thousands) from varying distances, the environmental impact just one conference can have is tremendous. Hence, reducing the need for in-person conferences by improving the digital discussion space could reduce greatly reduce the environmental impact of communicating and discussing research (demand 14). By not fully harnessing digital possibilities for virtual conferencing, in-person meetings will remain the preferred option. Such travel for in-person meetings is also expensive and raises costs to participate in research, effectively undermining efforts to increase accessibility of science (e.g., demand 1).

Productive digital spaces to engage in continuous discussion exist, but do not substantially change the evaluation of contributions (demands 8, 9), limit access to affiliated researchers (demand 1), surveill users to collect data to monetize in the form of advertising (demand 16), and may give rise to new monopolies or oligarchies (demand 17). The most notable example of this is ResearchGate, which has effectively reproduced Facebook's model but in a research environment. By monetizing the data collected on users by advertising either scientific products, services, or job postings, they have created a revenue model. Also similar to Facebook, they have a commercial incentive to retain (or lock in) users on their platform and moderate the platform; they severely affect the accessibility by not allowing pseudonymous postings [which would make contributions like Student's t-distriubtion impossible; @] and make themselves the gatekeeper of content. The platformization of science is problematic for the very same reason the publishing houses are so problematic in the transition to open access; there is the risk of creating a severe dependency that is harmful to the progress of science. Moreover, with the issues currently developing at Facebook and Twitter with respect to moderating their platforms, we see creating just another social platform has issues that also need to be tackled. Luckily, no one platform has come out on top just yet [@doi:10.1038/512126a] and there's time to produce alternatives for science.

Alternative ways of funding might help sustain participatory co-creative processes outside universities. Substantial public and philanthropic research funds tend to go towards institutions that have sufficient support staff to account for all the bureaucratic requirements, which makes these kinds of funds uninviting and virtually impossible for independent researchers and non-traditional institutions. As such, co-creative funding processes might be more facilitating of such dynamic research groups. Such co-creative funding streams might be built on revenue models that commodify consumption of knowledge instead of access to it. Despite using its revenue for other purposes than funding, a service like ResearchGate shows there is substantial interest in alternative ways for researchers to connect and share information. The acquisitions of traditional publishers indicate they are consolidating their technical capital to own a way to facilitate the entire research process from ideation to review to communication (e.g., Elsevier buying Mendeley, Bepress, Aries systems). However, these businesses are simply coopting developments in the research space, moving from privatized publishing models to privatized platformizatoin [@doi:10.1177/0306312718772086]. Research communities may consider building these innovations themselves, in order to regain some form of governance from the private sphere and to capitalize on opportunities that can subsequently be used to fund different types of research. It may be naive to think businesses will share considerable amounts of revenue voluntarily to fund research if left to their own devices, but researchers could coopt the commercial space for research's benefit. After all, the commercial sector coopted the research space with publishing for the benefit of their profits.


<!-- how to implement -->
Of course, just talking about a utopia is a form of science populism


<!-- talk about barriers to change -->
If we talk about letting utopia take place on the Internet, we need to account for the fact that half of the world's population has no such access.



Increasing ways to digest the produced knowledge
* evaluation as a research process, not generic metrics
* simple landscape to navigate, many ways to navigate (instead of complex landscape to navigate, one way to navigate)
* curation choice => do it yourself, let others do it, or have a machine do it (or all)
* prestige through contributions in a co-creative process that 
* author controls style and is responsible (no more typesetting frustration)
* research quality is a driver of research prestige
* shadow work is recognized in full worth of its added contributions; reward all contributions not only papers
* facilitate people's  strength through allowing them to specialize
  * level out the playing field (instead of making technician subordinate to prof)
* format is adapted to the content, not the content to the format (Supplement eiko)
  * communicate when you want to and how you decide to (no more journal giudelines)
<!-- 
 -->
 * open the system to reform more
* no centralization/platformization => Facebook, ResearchGate
* Intellectual property no longer restricts research directly or indirectly
* independent of the existence of certain institutions
    * COS Open source nature but infrastructure implementation no go https://api.crossref.org/members/15934

* internet access



<!-- limited access creates an availability bias -->
<!-- https://api.oadoi.org/10.1002/asi.22784?email=chjh@pm.me -->
<!-- cost of accessing DOIs in this dissertation -->

https://onlinelibrary.wiley.com/doi/pdf/10.1111/joms.12344
https://www.biorxiv.org/content/early/2018/07/13/367847
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3204791
doi.org/10.1177/2515245918754485

https://www.nature.com/articles/d41586-018-05789-4
https://twitter.com/lteytelman/status/1021814235599269888


<!-- link to dat and no internet zones for accessibility and co-creation later-->

* Broken submission cycles
* Broken supplemental files
* Retractions corrections
* Bad indexing
* Inclusivity
  * Moving across the world for work
* Publication delays
* Cybersecurity
  * DDoS
  * Supplemental materials
* Pseudo-open
10.1177/1461444810365297 bot wikipedia  
https://doi.org/10.1111/j.1468-2958.2002.tb00828.x
https://twitter.com/rmounce/status/1021315774353485824
https://www.journals.uchicago.edu/doi/suppl/10.1086/697113


* language issues
  http://stm.sciencemag.org/content/8/341/341ps12.short
* even those who try hard fail
  * broken links (eg in data paper to github page)
* Sustainability
  * COS [audit reports](https://cos.io/about/our-finances/)
    * Its origins https://thesiscommons.org/t23za/
* Open Science
  * Data sharing
  https://osf.io/preprints/bitss/39cfb/
  https://www.cureus.com/articles/10474-data-sharing-in-neurosurgery-and-neurology-journals
  https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/data-access-transparency-and-replication-new-insights-from-the-political-behavior-literature/64CA07CBA652E299079FF32BC5A6DCB3
* Publication bias
  https://link.springer.com/article/10.3758/s13423-018-1451-8
  * registries are insufficient
  http://www.fww.ovgu.de/fww_media/femm/femm_2017/2017_19.pdf
  * Preregistration is not catching on
    * preregistration challenge
    * https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01832/full
  * methods to correct suffer from their own issues
    https://econtent.hogrefe.com/doi/abs/10.1027/2151-2604/a000319?journalCode=zfp
    puniform
    * best is to not have to use these methods to begin with
  * chrysalis effect
    http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0192219
  https://www.sciencedirect.com/science/article/pii/S0028393218301076
  * insanely harmful for incentives
    http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2000995
    https://elifesciences.org/articles/21451
    * Registered reports
    https://twitter.com/Jopdevrieze/status/1016991218033717249
  * detecting fabrication also needs removal of publication bias (see ch6)
* harmful aspects of replications
  https://dl.acm.org/citation.cfm?id=3183423
  http://journals.sagepub.com/doi/abs/10.1177/1745691616646366
* Self-correcting is myth
  http://www.pnas.org/content/early/2018/03/08/1708276114
  http://journals.sagepub.com/doi/abs/10.1177/2515245918771329
* monolithic certification culture through gold standard peer review
* NHST v Bayesian debate
  * small samples
  https://www.nature.com/articles/s42003-018-0073-z
  https://link.springer.com/article/10.3758/s13423-018-1451-8
  * procedural tightening
  http://journals.sagepub.com/doi/abs/10.1177/1745691617745651
  http://journals.sagepub.com/doi/abs/10.1177/1745691617753947
  http://journals.sagepub.com/doi/abs/10.1177/1745691617739421
  http://journals.sagepub.com/doi/abs/10.1177/1745691618773326
  https://www.nature.com/articles/s41562-017-0189-z
  * statistical power is not the most importnat
  http://journals.sagepub.com/doi/abs/10.1177/0956797616647519
  <!-- https://dash.harvard.edu/bitstream/handle/1/37171537/611615/whichfindings.pdf?sequence=1 -->
* Credit
https://www.nature.com/articles/palcomms2016105#notes
  http://www.mdpi.com/2304-6775/6/2/18
  http://journals.sagepub.com/doi/abs/10.1177/2515245918758319
  http://psycnet.apa.org/record/2018-06770-004
  * badges
    http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002456
    https://f1000research.com/articles/7-90/v2
  * predatory journals are symptom of incentive system

http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2006843
    http://journals.sagepub.com/doi/full/10.1177/2515245918773742 => protocol review at the lancet 1997-2015
  * https://www.gwern.net/docs/statistics/peerreview/2015-lancet.pdf
* preprints
http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002549
* catering to heterogeneous researchers and research
  https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3154143
  five schools of open science

## Where to start
* education
  * autodidactic
    https://psyarxiv.com/gxcy5
    https://collabra.org/articles/10.1525/collabra.158/
    https://books.google.de/books?hl=en&lr=&id=NDEyDwAAQBAJ&oi=fnd&pg=PR11&ots=xB51GPCLPl&sig=ZD78syEfexsGgFeSw1basz0FZyg#v=onepage&q&f=false
  * institutional
  http://journals.sagepub.com/doi/abs/10.1177/0098628318762900
  * supervisional
  https://www.frontiersin.org/articles/10.3389/fnhum.2016.00153/full
  https://link.springer.com/article/10.3758/s13423-017-1317-5
  https://link.springer.com/article/10.3758/s13423-017-1266-z

* adverserial collabs
  https://www.sciencedirect.com/science/article/pii/S0022103117306352
* process focussed
  http://journals.sagepub.com/doi/abs/10.1177/1745691618767883

* empowerment
http://journals.sagepub.com/doi/abs/10.1177/1359105316675213

- [ ] https://scholar.google.nl/scholar?cites=16149438710536643567&as_sdt=2005&sciodt=0,5&hl=en
- [ ] reproducibility manifesto
- [ ] TOP guidelines
<!-- http://www.pnas.org/content/early/2018/03/08/1708274114.short -->
http://orca.cf.ac.uk/59475/
- [ ] http://journals.sagepub.com/doi/abs/10.1177/2515245918771329
- [ ] https://faculty.wharton.upenn.edu/wp-content/uploads/2017/05/Nelson-Simmons-Simonsohn-2018.pdf
  * http://psycnet.apa.org/record/1999-04258-000

### RPP

https://www.researchgate.net/profile/Isabelle_Bartram/publication/324825190_Knowledge_in_the_Dark_Scientific_Challenges_and_Ways_Forward/links/5ae4d138458515760ac080bb/Knowledge-in-the-Dark-Scientific-Challenges-and-Ways-Forward.pdf
http://journals.sagepub.com/doi/abs/10.1177/1745691618767878
http://philsci-archive.pitt.edu/14410/
http://journals.sagepub.com/doi/abs/10.1177/1745691615609918
https://www.annualreviews.org/doi/abs/10.1146/annurev-criminol-032317-091849
http://journals.sagepub.com/doi/abs/10.1177/1745691617698146
https://bmcpsychology.biomedcentral.com/articles/10.1186/s40359-016-0126-3

https://www.biorxiv.org/content/early/2018/07/13/367847

Fake news, fake science, used to not criticize established scientists and undermine meta efforts to improve science

https://twitter.com/g3om4c/status/1022471865330225152
https://twitter.com/BrianNosek/status/1022562056665554945
preprints being indexed in crossref and in article
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0091819
http://journals.sagepub.com/doi/10.1177/0016986218784178
http://journals.sagepub.com/doi/10.1177/2332858418787466
https://osf.io/zqr69/
https://www.nature.com/articles/d41586-018-05754-1
https://link.springer.com/article/10.1007/s11192-018-2848-x
https://www.nature.com/articles/d41586-018-05751-4
https://www.nature.com/articles/d41586-018-05750-5
https://www.nature.com/articles/d41586-018-05749-y
https://www.slideshare.net/vtraag/uncovering-important-intermediate-publications-103598761
<!-- https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/making-replication-mainstream/2E3D8805BF34927A76B963C7BBE36AC7#fndtn-related-commentariess -->
<!-- pipeline https://www.sciencedirect.com/science/article/pii/S0022103115300019 -->
<!-- http://journals.sagepub.com/doi/abs/10.1177/1745691616658637 -->
<!-- https://onlinelibrary.wiley.com/doi/abs/10.1111/infa.12182 -->

## Scenario

team of engineers creates schematics for co2 measurement device
scientists validate the device
a third party mass produces the device and uses part of the revenue for profit, part to fund applications of the device
a teachers discover this and conspire to apply for a national project
devices delivered to the teachers
call to scientists for strict measurement protocol
children go out and produce their first scientific contribution
researchers join the data and analyze
a retired educational researcher 

## Conclusion

If we solely focus on reproducibility in science, we lack to recognize the larger context the scientific pursuit takes place in. There 
