#!/usr/bin/env Rscript

bookdown::preview_chapter('01-scienceopen.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('02-peerj_reanalyzing.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('03-peerj_bump.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('04-tgtbf.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('05-statcheck.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('06-ddfab.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('07-vector.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('08-asyougo.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('09-datcom.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('10-summary.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('11-discussion.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('12-appendices.Rmd', 'bookdown::gitbook')
bookdown::preview_chapter('index.Rmd', 'bookdown::gitbook')

 bookdown::preview_chapter('01-scienceopen.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('02-peerj_reanalyzing.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('03-peerj_bump.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('04-tgtbf.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('05-statcheck.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('06-ddfab.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('07-vector.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('08-asyougo.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('09-datcom.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('10-summary.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('11-discussion.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('12-appendices.Rmd', 'bookdown::pdf_book')
bookdown::preview_chapter('index.Rmd', 'bookdown::pdf_book')

bookdown::render_book("index.Rmd", "bookdown::gitbook")
# bookdown::render_book("index.Rmd", "bookdown::pdf_book")
# bookdown::render_book("index.Rmd", "bookdown::epub_book")
